org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/RunServer.java
=> updated to lsp #16

build.gradle, org.xtext.example.mydsl.ide/build.gradle, vscode-extension-self-contained/build.gradle, vscode-extension-self-contained/src/extension.ts
This change gets rid of the shadow jars and uses the Gradle application plugin which has better start scripts.
Also the task inputs / outputs have been improved - this yields a better incremental build.
=> use Gradle application plugin

build.gradle, org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/ServerLauncher.xtend, vscode-extension-self-contained/package.json, vscode-extension/package.json
=> npm + lsp4j update

build.gradle, gradle/wrapper/gradle-wrapper.properties, vscode-extension-self-contained/build.gradle
=> new gradle version, better windows support, cleanup deprecated stuff

build.gradle, org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/EclipseLikeHoverService.xtend
=> update to 2.13

build.gradle
=> use newer version of release plugin

org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/CommandService.xtend, org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeModule.xtend, vscode-extension-self-contained/package.json, vscode-extension-self-contained/src/extension.ts, vscode-extension/package.json, vscode-extension/src/extension.ts
=> added an example for command service

org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeSetup.xtend
=> [#30] recreated MyDslIdeSetup to ensure startability with Xtext 2.14

build.gradle, org.xtext.example.mydsl.websockets/build.gradle, org.xtext.example.mydsl.websockets/src/org/xtext/example/mydsl/websockets/RunWebSocketServer2.xtend, org.xtext.example.mydsl.websockets/src/org/xtext/example/mydsl/websockets/RunWebSocketServer3.xtend, vscode-extension-self-contained/package.json, vscode-extension/package.json
=> websocket stuff and lsp/xtext update

org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeModule.xtend, org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/contentassist/CustomContentAssistService.java
=> added workaround for xtext 2.15 content assist service bug

org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslCodeActionService.xtend, org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeModule.xtend
=> quickfix example

vscode-extension-self-contained/package.json, vscode-extension/package.json
=> fixed package.json warnings

atom-extension/LICENSE.txt, atom-extension/package.json
=> aligned versions

atom-extension/build.gradle
=> introduced task called atomExtension

vscode-extension-self-contained/src/extension.ts
=> #21 fixed debugging

theia-extension/.gitignore, theia-extension/.vscode/launch.json, theia-extension/README.md, theia-extension/browser-app/package.json, theia-extension/lerna.json, theia-extension/mydsl-extension/data/mydsl.tmLanguage.json, theia-extension/mydsl-extension/package.json, theia-extension/mydsl-extension/src/browser/mydsl-contribution.ts, theia-extension/mydsl-extension/src/browser/mydsl-frontend-module.ts, theia-extension/mydsl-extension/src/browser/mydsl-grammar-contribution.ts, theia-extension/mydsl-extension/src/browser/mydsl-language-client-contribution.ts, theia-extension/mydsl-extension/src/common/index.ts, theia-extension/mydsl-extension/src/node/mydsl-backend-module.ts, theia-extension/mydsl-extension/src/node/mydsl-language-server-contribution.ts, theia-extension/mydsl-extension/tsconfig.json, theia-extension/package.json, theia-extension/theia-version.sh
=> theia example

atom-extension/README.md, atom-extension/package.json
=> enabled code actions

build.gradle
=> use 2.17.0.M1

build.gradle
=> update to 2.17

build.gradle, vscode-extension-self-contained/package.json, vscode-extension/package.json
=> bump to 2.17.1 / newer vscode

build.gradle
=> update to 2.18

.travis.yml
=> fixed travis build

atom-extension/build.gradle, build.gradle
=> use newer gradle plugins for node and xtend

build.gradle
=> bumped gradle node plugin to fix gradle 5.0 deprecations

build.gradle
=> updated node-gradle plugin to new 2.0 version

org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslCodeActionService.xtend, org.xtext.example.mydsl.ide/src/org/xtext/example/mydsl/ide/MyDslIdeModule.xtend
updated to new code action api
=> updated to new code action api

org.xtext.example.mydsl/src/org/xtext/example/mydsl/generator/MyDslGenerator.xtend
=> fixed encoding in generator

build.gradle
=> build against 2.19 release

build.gradle
=> sunset jcenter
